#!/bin/sh
chmod 755 /usr/lib/enigma2/python/Plugins/Extensions/E2Doctor/plugin.py 2>/dev/null || true
chmod 755 /usr/bin/e2doctor-report 2>/dev/null || true
chmod 644 /usr/lib/enigma2/python/Plugins/Extensions/E2Doctor/logo_hd.png 2>/dev/null || true
chmod 644 /usr/lib/enigma2/python/Plugins/Extensions/E2Doctor/logo_fhd.png 2>/dev/null || true
mkdir -p /etc/enigma2/e2doctor/backups 2>/dev/null || true
exit 0
